import type { Document } from "@/lib/domain";

/**
 * Placeholder demo PDFs, generated programmatically — tiny but VALID
 * single-page PDF 1.4 files (catalog → pages → page → Helvetica text, correct
 * xref offsets), so "View CV" in the demo opens a real PDF viewer instead of
 * 404ing. No binary assets are committed; the bytes are built on demand.
 */

function pdfEscape(text: string): string {
  return text.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}

/** Build a minimal valid one-page PDF with the given lines of text. */
export function buildDemoPdf(lines: string[]): Buffer {
  const textOps = lines
    .map(
      (line, i) =>
        `BT /F1 ${i === 0 ? 20 : 12} Tf 72 ${760 - i * 28} Td (${pdfEscape(line)}) Tj ET`,
    )
    .join("\n");
  const stream = textOps;

  const objects: string[] = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    `<< /Length ${Buffer.byteLength(stream, "utf8")} >>\nstream\n${stream}\nendstream`,
  ];

  let body = "%PDF-1.4\n";
  const offsets: number[] = [];
  objects.forEach((obj, i) => {
    offsets.push(Buffer.byteLength(body, "utf8"));
    body += `${i + 1} 0 obj\n${obj}\nendobj\n`;
  });

  const xrefStart = Buffer.byteLength(body, "utf8");
  let xref = `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const off of offsets) xref += `${String(off).padStart(10, "0")} 00000 n \n`;
  const trailer = `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF\n`;

  return Buffer.from(body + xref + trailer, "utf8");
}

/** Demo PDF catalog: served by /api/files/pdf/[name] in demo mode. */
const DEMO_PDF_LINES: Record<string, string[]> = {
  "demo-cv-nimbus-labs.pdf": [
    "Alex Doe - CV (demo)",
    "Tailored for: Nimbus Labs - Design Engineer",
    "",
    "This is a fictional placeholder document generated by the",
    "career-ops-web demo. No real CV content is shipped.",
  ],
  "demo-cover-nimbus-labs.pdf": [
    "Cover letter (demo)",
    "Nimbus Labs - Design Engineer",
    "",
    "Fictional placeholder generated by the career-ops-web demo.",
  ],
  "demo-cv-halcyon-grid.pdf": [
    "Alex Doe - CV (demo)",
    "Tailored for: Halcyon Grid - Product Engineer, AI Console",
    "",
    "This is a fictional placeholder document generated by the",
    "career-ops-web demo. No real CV content is shipped.",
  ],
};

export function getDemoPdf(name: string): Buffer | null {
  const lines = DEMO_PDF_LINES[name];
  if (lines) return buildDemoPdf(lines);
  // Generic placeholder for any generated demo doc (CV / cover letter) so the
  // library previews never 404 in demo mode.
  if (/^demo-(cv|cover)-.+\.pdf$/i.test(name)) {
    const kind = /^demo-cover-/i.test(name) ? "Cover letter" : "CV";
    return buildDemoPdf([
      `${kind} (demo)`,
      name,
      "",
      "Fictional placeholder generated by the career-ops-web demo.",
      "No real document content is shipped.",
    ]);
  }
  return null;
}

/** Document entries surfaced by DemoDataSource.getDocuments. */
export const DEMO_DOCUMENTS: Record<number, Document[]> = {
  1: [
    { kind: "cv", appNum: 1, fileName: "demo-cv-nimbus-labs.pdf", path: "output/demo-cv-nimbus-labs.pdf" },
    { kind: "cover-letter", appNum: 1, fileName: "demo-cover-nimbus-labs.pdf", path: "output/demo-cover-nimbus-labs.pdf" },
  ],
  12: [
    { kind: "cv", appNum: 12, fileName: "demo-cv-halcyon-grid.pdf", path: "output/demo-cv-halcyon-grid.pdf" },
  ],
};
