"use client";

import type { Recommendation } from "@/lib/domain";
import { ChartCard, ChartEmpty } from "./chart-card";

/**
 * Recommendations from analyze-patterns.mjs, rendered VERBATIM (F5 AC) —
 * action, reasoning, and impact are the script's own words, never rephrased.
 */
export function RecommendationsCard({
  recommendations,
}: {
  recommendations: Recommendation[];
}) {
  return (
    <ChartCard
      title="Recommendations"
      subtitle="Generated by analyze-patterns.mjs — shown verbatim."
    >
      {recommendations.length === 0 ? (
        <ChartEmpty>No recommendations yet — keep applying.</ChartEmpty>
      ) : (
        <ul className="flex flex-col divide-y">
          {recommendations.map((rec) => (
            <li key={rec.action} className="flex flex-col gap-1 py-3 first:pt-0 last:pb-0">
              <div className="flex items-start justify-between gap-3">
                <p className="text-data font-medium">{rec.action}</p>
                <span className="shrink-0 rounded-sm border px-1.5 py-0.5 font-mono text-[11px] text-muted-foreground">
                  {rec.impact}
                </span>
              </div>
              <p className="text-data text-muted-foreground">{rec.reasoning}</p>
            </li>
          ))}
        </ul>
      )}
    </ChartCard>
  );
}
